version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 42
  ignore:
  - dependency-name: "Microsoft.Extensions.*"
    versions: ">= 5.0.0"
  - dependency-name: "Microsoft.AspNetCore.*"
    versions: ">= 5.0.0"
  - dependency-name: "Microsoft.EntityFrameworkCore.*"
    versions: ">= 5.0.0"