version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Z.EntityFramework.Plus.EFCore
    versions:
    - 5.1.15
    - 5.1.16
    - 5.1.17
    - 5.1.19
    - 5.1.23
    - 5.1.24
    - 5.1.25
    - 5.1.26
    - 5.1.27
    - 5.1.28
    - 5.1.29
    - 5.1.30
    - 5.1.31
  - dependency-name: Microsoft.EntityFrameworkCore.InMemory
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Mvc.NewtonsoftJson
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: AutoMapper.Extensions.ExpressionMapping
    versions:
    - 4.1.0
  - dependency-name: Microsoft.Extensions.Primitives
    versions:
    - 5.0.0
